%% EN.530.646 RDKDC - Final Project
% _*Group 7*_


%%  TwoEndAboveOffset( )
%
% * Purpose:
%   Used in drawing graphic by the UR5 to prevent segments by overlapping
%   
%
% * Input:
%   *q_list*: 6xn matrix which contains all the joints angles in an area
%
%   *above_offset*: the height offset parameters which comes in meters.
%
%   *idx*: index position generated by Inverse Kinematics
%
% * Output:
%   *Offseted_q_list*: 6x(n+2) matrix which add the first point above joint
%                      angles and last point above joint angles


function Offseted_q_list = TwoEndAboveOffset(q_list, above_offset, idx)

    g_above_offset = [zeros(4,3),[0; 0; above_offset; 0]];

    g_start_above = ur5FwdKin(q_list(:,1)) + g_above_offset;
    IK_Joints_start_above = ur5InvKin(g_start_above);
    q_start_above = IK_Joints_start_above(:,idx);

    g_end_above = ur5FwdKin(q_list(:,length(q_list))) + g_above_offset;
    IK_Joints_end_above = ur5InvKin(g_end_above);
    q_end_above = IK_Joints_end_above(:,idx);

    Offseted_q_list = [q_start_above, q_list, q_end_above];

end